# # RUN line below for dev & test # #
# docker-compose -p mynute-go-auth -f services/auth/docker-compose.dev.yml up -d --force-recreate

services:
  postgres:
    image: postgres:17.5
    restart: always
    stop_grace_period: 30s
    stop_signal: SIGTERM
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_PROD=${POSTGRES_DB_PROD}
      - POSTGRES_DB_TEST=${POSTGRES_DB_TEST}
      - POSTGRES_DB_DEV=${POSTGRES_DB_DEV}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - mynute-auth-network
   
networks:
  mynute-auth-network:

volumes:
  postgres-data:
