global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mynute-auth-service'
    static_configs:
      - targets: ['localhost:4001']
        labels:
          service: 'auth'
          environment: 'production'
