global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mynute-email-service'
    static_configs:
      - targets: ['localhost:4002']
        labels:
          service: 'email'
          environment: 'production'
